### ISSUE TITLE
Unable to drag items in Settings

### ISSUE THREAD

**Issue by KenLucke** [jneilliii/OctoPrint-TerminalCommandsExtended#20] opened 2020-11-23 22:47 UTC
Since the update, I cannot drag the buttons around in the settings dialog.  I can create them, delete them, and get tooltips and cursor changes when mousing over them, but clicking and dragging them has no effect.

Mac OSX 15.5.7, Firefox and Safari, OctoPrint 1.4.2, TCE v0.1.6, Python v2.7.16 (no, I haven't updated, as 3.x broke a bunch of favorite plugins and I downgraded)

**Comment by jneilliii** [comment] 2020-11-24 09:31
Are there any errors in the developer console on initial page load?

**Comment by KenLucke** [comment] 2020-11-24 10:55
Not sure if this is what you are  looking for, but clearing the console, then reloading OctoPrint and going to the plugins settings and TCE  dialog, this is the result  (Errors and Warnings only):


```
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). onloadwff.js:71:799505
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). 3 utils.js:35:9
Content Security Policy: The page’s settings blocked the loading of a resource at data: (“media-src”).
Some cookies are misusing the recommended “SameSite“ attribute 5
Cookie “session_P443” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite languages
Cookie “session_P443” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite languages
Cookie “session_P443” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite 2 printerprofiles
Cookie “session_P443” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite 2 appkeys
Cookie “session_P443” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite 2 backup
```

**Comment by jneilliii** [comment] 2020-11-24 17:56
Thanks, confirmed bug. Something must have got messed up with all the moving of components around. I will investigate further.

**Comment by KenLucke** [comment] 2020-11-24 18:03
Cool, looking forward to an update.  Easy to break stuff when adding new functionality.

**Comment by jneilliii** [comment] 2020-11-24 18:03
Found it, I removed the sortable binding, I think I just need to add it back [here](https://github.com/jneilliii/OctoPrint-TerminalCommandsExtended/blob/1570b31cd5aa7ef1d9dcfc4dd7cd032c664d22c9/octoprint_terminalcommandsextended/templates/terminalcommandsextended_settings.jinja2#L9) instead of using the foreach binding. I'll test this in a little bit and get back with you.

**Comment by KenLucke** [comment] 2020-11-24 18:07
> Found it, I removed the sortable binding, I think I just need to add it back [here](https://github.com/jneilliii/OctoPrint-TerminalCommandsExtended/blob/1570b31cd5aa7ef1d9dcfc4dd7cd032c664d22c9/octoprint_terminalcommandsextended/templates/terminalcommandsextended_settings.jinja2#L9) instead of using the foreach binding. I'll test this in a little bit and get back with you.

That was fast. Must have taken your speedy pills this morning. :)

**Comment by jneilliii** [comment] 2020-11-24 18:49
Yeah, this is going to be more involved than I originally thought. Because of the settings interface providing a preview of the ordering it's breaking the link to the underlying config settings. Not really sure the best way to move forward on this one, but need to check into the available options for the sorting. For now I think switching this back to a simple list rather than the preview is going to be the quick fix for ordering, but then has the negative side effect of not being able to see how your offsets/widths will look.

**Comment by KenLucke** [comment] 2020-11-24 18:57
I can live with that for now.  :)

**Comment by jneilliii** [comment] 2020-11-24 19:11
You can copy/paste the URL below in Plugin Manager > Get More > ...from URL and click Install to verify for more it's working again.

```
https://github.com/jneilliii/OctoPrint-TerminalCommandsExtended/archive/0.1.7rc1.zip
```

**Comment by KenLucke** [comment] 2020-11-24 20:12
Will do, but all printers are engaged at this time, so it will be about 12  hours before one of  them is done to be able to do so.,

**Comment by KenLucke** [comment] 2020-11-24 20:13
I might fire up the spare Pi and update everything, then try it... but I'm working on Christmas decorations today... I have [literally] about 20,000 lights to put up.

**Comment by KenLucke** [comment] 2020-11-25 16:04
Sorry, no joy.  Same unable to drag buttons.

**Comment by jneilliii** [comment] 2020-11-25 20:18
My bad, Ken, I based that release on the wrong branch. It should be fixed now, so if you reinstall using the same URL above it should be fixed for real now.

**Comment by KenLucke** [comment] 2020-11-26 01:40
Dragging has been reenabled, but as you drag, the point where the button shows and the point where the cursor shows are not the same, making it difficult to determine where you are about to drop the button.  Takes some getting use to.

**Comment by jneilliii** [comment] 2020-11-26 02:12
Yeah, I noticed that on some buttons, but not all of them for some reason. Definitely needs some more debugging.

**Comment by KenLucke** [comment] 2020-11-26 02:21
Well, at least they are draggable, and I was able to get my layout done.  Now when the buttons match the width, it will look awesome.
![CR-10 v2 (Blue) LAN  OctoPrint  2020-11-25 18-21-42](https://user-images.githubusercontent.com/57936294/100300559-22ede200-2f4b-11eb-90b4-af664747d305.jpg)

**Comment by jneilliii** [comment] 2020-11-26 07:04
Dragging might be better in this version.

```
https://github.com/jneilliii/OctoPrint-TerminalCommandsExtended/archive/0.1.7rc2.zip
```

**Comment by KenLucke** [comment] 2020-11-26 21:06
Dragging IS much better, and column sizing is beautiful!

<img width="910" alt="image" src="https://user-images.githubusercontent.com/57936294/100391411-300cde80-2fe8-11eb-801c-8ae42157d037.png">

**Comment by KenLucke** [comment] 2020-11-26 21:09
Only ONE last request on this one for now :)

When clicking  "Duplicate Button," could you duplicate it at that spot (immediately after the button being clicked to duplicate) instead of at the bottom ("Create Button/Break" would still make a new one at the bottom)?  It would eliminate much dragging and scrolling for those of us with large, complicated lists of buttons.

**Comment by jneilliii** [comment] 2020-11-26 22:39
That might be possible to achieve, just have to dig into the js code to figure out how to add the duplicate in at a specifici position of the observableArray. Might be tricky, but I'll take a look.

**Comment by EagleB3** [comment] 2020-12-01 09:31
FireFox v.83.0 x64, plugin 0.1.7rc2.zip

The "crosses" for dragging are hidden by objects of other buttons. Clearing the cache in the browser doesn't help.
![TCE v 1 7 RC2 and OctoPrint v 1 5 0](https://user-images.githubusercontent.com/43371261/100720464-147e4b00-33cf-11eb-9e99-d4750bac7b37.png)

**Comment by jneilliii** [comment] 2020-12-01 13:22
You don't have any widths defined do you @EagleB3?

**Comment by EagleB3** [comment] 2020-12-01 13:31
@jneilliii , I may not understand the question correctly, but it looks like the answer = "Yes". 
The labels overlap each other. In the screenshot, the cursor is hovering over the label "G30Z0", but its service fields remain closed by the label located to the right of the "G30Z0":
![Selected](https://user-images.githubusercontent.com/43371261/100746969-7c925880-33f2-11eb-91a2-250a6a907853.png)

Could it be that somewhere in the plugin settings there is not cleared cache or temporary files?

**Comment by jneilliii** [comment] 2020-12-01 18:21
Yeah the changes that I did to accommodate #21  has inadvertently made this happen I think.  I'll look into it further to try and get a happy medium. I think if your buttons width was defined it would spread those out more or this is a problem with firefox rendering.

![image](https://user-images.githubusercontent.com/5249455/100780798-2ca69800-33d8-11eb-8918-35d900339b5a.png)

**Comment by EagleB3** [comment] 2020-12-01 18:34
Yes it is. Here's how the buttons look in the settings for the different widths they define:
![Width123](https://user-images.githubusercontent.com/43371261/100782076-f4757880-341c-11eb-930d-e12641eb885b.png)

**Comment by KenLucke** [comment] 2020-12-01 19:07
The key is to set a minimum of 2-3 for width, drag them to where you want them, then set the width lower if need be (why you'd ever want a width of 1, I don't know, unless there was no text).  You could also temporarily increase the offset of the _next_ button to space it out, then reduce later.

Unless you set a  min width in the settings window, which would make it not represent the real window properly, I'm not sure that there is a solution for this.  One thing that might help is when a new button is created, pre-set a width of 2 or 3.

**Comment by KenLucke** [comment] 2020-12-01 19:11
The key is to set a minimum of 2-3 for width, drag them to where you want them, then set the width lower if need be (why you'd ever want a width of 1, I don't know, unless there was no text).  You could also temporarily increase the offset of the _next_ button to space it out, then reduce later.

@jneilliii, Unless you set a  min width in the settings window, which would make it not represent the real window properly, I'm not sure that there is a solution for this.  One thing that might help is when a new button is created, pre-set a width of 2 or an offset of 1.

**Comment by jneilliii** [comment] 2020-12-01 19:14
I do default the width to three when you add the button. I'm sure I'll be able to figure something out. The issue is all in the css and inline blocking versus not blocking. The way it is now (non-blocking) allows for the smaller widths to overlay each other. It will be tricky, but I bet I can figure some kind of css hack out for this.

**Comment by jneilliii** [comment] 2020-12-01 19:15
I do like the idea of handling width 0 as "just make it work like before" in #24

**Comment by EagleB3** [comment] 2020-12-02 12:33
Forgive my poor knowledge of English - I am not sure that I understood the essence of the discussed issue correctly. But I want to draw your attention to the fact that the appearance and position of the buttons within some limits can be seen immediately after creation / modification, even without saving the changes made to the settings.
Unfortunately, when invoking the settings window, the Octoprint interface always moves the window to the left and up, and does not allow you to move the open settings window around the screen. Still, you can see the final appearance of the buttons (especially if the buttons are compact!)
![W-2](https://user-images.githubusercontent.com/43371261/100872830-77e1a900-34b3-11eb-85de-00e5f60db6b2.png)
![M-2](https://user-images.githubusercontent.com/43371261/100872850-7dd78a00-34b3-11eb-9763-2cc7de4e8611.png)

**Comment by EagleB3** [comment] 2020-12-02 12:43
Do you think it makes sense to ask Gina Häußge to make the settings window at least moveable on the screen? This feature would greatly simplify the issue of viewing the final location of the buttons, and perhaps completely solve it.
I am not sure that I can correctly and unambiguously describe this task... :(
![Move](https://user-images.githubusercontent.com/43371261/100874052-0a367c80-34b5-11eb-9ac4-e7f13e34157a.png)

**Comment by jneilliii** [comment] 2020-12-02 14:07
I think I understand what you mean. There is a way to do this programmaticaly, the UI Customizer plugin does it, I just need the time to work on this, I do have a full time job and do this in my spare time.

**Comment by garurumoon** [comment] 2021-04-22 21:20
Hello. I am experiencing the same issue as indicated in the original post. Is this a known issue? if not - how can I be helpful?

**Comment by jneilliii** [comment] 2021-04-22 21:27
@garurumoon could you test the latest rc version by changing the release channel for the plugin in OctoPrint's software update settings to `Release Candidate` and upgrade when prompted? I haven't had much time to work on this plugin, but think dragging may be working better in it, unless you have a plugin conflict that is loading a different jquery sortable library or not including it at all. If you are still experiencing issues with 0.1.7 rc2 I'll need a list of plugins that you have installed.

**Comment by garurumoon** [comment] 2021-04-22 21:33
The Release candidate worked, thank you.

**Comment by LouDnl** [comment] 2021-08-04 09:54
Sorry for replying to an old issue, but I still cannot move any buttons.
Plugin version is 0.1.6
Octopi version 0.17
Octoprint version 1.6.1

Other plugins:
<html>
<body>


OctoPrint: 1.6.1 Release Channel: StableMaintenance RCsDevel RCs Installed: 1.6.1Available: 1.6.1Release Notes: https://github.com/OctoPrint/OctoPrint/releases/tag/1.6.1
--
  | Arc Welder: Anti-Stutter: unknown Release Channel: StableMaintenance RCsDevel RCs Installed: ?Available: ?Unknown error while checking for update, please check the logs
  | Bed Visualizer: 1.1.0 Release Channel: StableRelease Candidate Installed: 1.1.0Available: 1.1.0 - Numpy RemovalRelease Notes: https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/releases/tag/1.1.0
  | BLTouch Plugin: 0.3.4 Release Channel: StableRelease Candidate Installed: 0.3.4Available: 0.3.4Release Notes: https://github.com/jneilliii/OctoPrint-BLTouch/releases/tag/0.3.4
  | Custom Control Editor Plugin: 0.2.2 Installed: 0.2.2Available: Version 0.2.2Release Notes: https://github.com/Salandora/octoprint-customControl/releases/tag/0.2.2
  | Dashboard Plugin: 1.18.3 Release Channel: StableRelease Candidate Installed: 1.18.3Available: 1.18.3Release Notes: https://github.com/j7126/OctoPrint-Dashboard/releases/tag/1.18.3
  | DisplayLayerProgress Plugin: 1.26.0 Installed: 1.26.0Available: V1.26.0Release Notes: https://github.com/OllisGit/OctoPrint-DisplayLayerProgress/releases/tag/1.26.0
  | Dragon Order: 0.1.7 Installed: 0.1.7Available: 0.1.7Release Notes: https://github.com/jneilliii/OctoPrint-DragonOrder/releases/tag/0.1.7
  | Filament Manager: 1.8.1 Installed: 1.8.1Available: V1.8.1Release Notes: https://github.com/OllisGit/OctoPrint-FilamentManager/releases/tag/1.8.1
  | File Check Plugin: 2021.2.23 Release Channel: StablePrerelease Installed: 2021.2.23Available: 2021.2.23Release Notes: https://github.com/OctoPrint/OctoPrint-FileCheck/releases/tag/2021.2.23
  | Firmware Check Plugin: 2021.5.31 Release Channel: StablePrerelease Installed: 2021.5.31Available: 2021.5.31Release Notes: https://github.com/OctoPrint/OctoPrint-FirmwareCheck/releases/tag/2021.5.31
  | Floating Navbar: 0.3.7 Release Channel: StableRelease Candidate Installed: 0.3.7Available: 0.3.7Release Notes: https://github.com/jneilliii/OctoPrint-FloatingNavbar/releases/tag/0.3.7
  | GCode System Commands: 1.0.1 Installed: 1.0.1Available: 1.0.1Release Notes: https://github.com/kantlivelong/OctoPrint-GCodeSystemCommands/releases/tag/1.0.1
  | Gcodebar Plugin: 0.1.5 Installed: 0.1.5Available: Python3 compabilityRelease Notes: https://github.com/mtowara/OctoPrint-Gcodebar/releases/tag/0.1.5
  | GcodeEditor Plugin: 0.2.12 Installed: 0.2.12Available: 0.2.12Release Notes: https://github.com/ieatacid/OctoPrint-GcodeEditor/releases/tag/0.2.12
  | M73 Progress Plugin: 0.2.1 Installed: 0.2.1Available: 0.2.1Release Notes: https://github.com/cesarvandevelde/OctoPrint-M73Progress/releases/tag/v0.2.1
  | MeatPack - Automatic G-Code Compression: 1.5.21 Installed: 1.5.21Available: Version 1.5.21 - Marlin FixesRelease Notes: https://github.com/scottmudge/OctoPrint-MeatPack/releases/tag/v1.5.21
  | MultiCam: 0.2.8 Installed: 0.2.8Available: Update Version InformationRelease Notes: https://github.com/mikedmor/OctoPrint_MultiCam/releases/tag/0.2.8
  | Navbar Temperature Plugin: 0.14 Installed: 0.14Available: 0.14 Milestone releaseRelease Notes: https://github.com/imrahil/OctoPrint-NavbarTemp/releases/tag/0.14
  | Octolapse: 0.4.1 Release Channel: StableMaintenance RCsDevel RCs Installed: 0.4.1Available: v0.4.1Release Notes: https://github.com/FormerLurker/Octolapse/releases/tag/v0.4.1
  | Pi Support Plugin: 2021.8.2 Release Channel: StablePrerelease Installed: 2021.8.2Available: 2021.8.2Release Notes: https://github.com/OctoPrint/OctoPrint-PiSupport/releases/tag/2021.8.2
  | PortLister: 0.1.10 Installed: 0.1.10Available: 0.1.10Release Notes: https://github.com/markwal/OctoPrint-PortLister/releases/tag/0.1.10
  | Preheat Button: 0.8.0 Installed: 0.8.0Available: Add preheat on file select feature and fix a UI bug with UI CustomizerRelease Notes: https://github.com/marian42/octoprint-preheat/releases/tag/0.8.0
  | Print Time Genius Plugin: 2.2.8 Installed: 2.2.8Available: Fix missing print history and height calculationRelease Notes: https://github.com/eyal0/OctoPrint-PrintTimeGenius/releases/tag/2.2.8
  | PSU Control: 1.0.6 Installed: 1.0.6Available: 1.0.6Release Notes: https://github.com/kantlivelong/OctoPrint-PSUControl/releases/tag/1.0.6
  | PSU Control - RPi.GPIO: 1.0.4 Installed: 1.0.4Available: 1.0.4Release Notes: https://github.com/kantlivelong/OctoPrint-PSUControl-RPiGPIO/releases/tag/1.0.4
  | Resource Monitor: 0.3.4 Release Channel: StablePrerelease Installed: 0.3.4Available: 0.3.4Release Notes: https://github.com/Renaud11232/OctoPrint-Resource-Monitor/releases/tag/0.3.4
  | SnapStream: 0.3 Installed: 0.3Available: 0.3Release Notes: https://github.com/markwal/OctoPrint-SnapStream/releases/tag/0.3
  | Tab Order: 0.5.12 Release Channel: StableRelease Candidate Installed: 0.5.12Available: 0.5.12Release Notes: https://github.com/jneilliii/OctoPrint-TabOrder/releases/tag/0.5.12
  | Terminal Commands Extended: 0.1.6 Release Channel: StableRelease Candidate Installed: 0.1.6Available: 0.1.6Release Notes: https://github.com/jneilliii/OctoPrint-TerminalCommandsExtended/releases/tag/0.1.6
  | Themeify: 1.2.2 Installed: 1.2.2Available: v1.2.2Release Notes: https://github.com/Birkbjo/OctoPrint-Themeify/releases/tag/v1.2.2
  | Z Probe Offset Control: 0.5 Installed: 0.5Available: 0.5


</body>
</html>

**Comment by jneilliii** [comment] 2021-08-04 14:34
I think the issue for you might be the custom control editor plugin. We both use the same jquery draggable UI and the one in that repo is outdated and doesn't include everything. If it overwrites my import than it makes my plugins not work. You can disable that plugin once you have the settings configured the way you like it and the custom controls will remain, as that is part of core OctoPrint and the plugin just exposes the settings in the UI. It's either that are you are not running the release candidate version of the plugin that fixed it. Swith the release channel in the software update settings of OctoPrint for the plugin and set it to release candidate and upgrade when prompted.

**Comment by LouDnl** [comment] 2021-08-05 19:05
> I think the issue for you might be the custom control editor plugin. We both use the same jquery draggable UI and the one in that repo is outdated and doesn't include everything. If it overwrites my import than it makes my plugins not work. You can disable that plugin once you have the settings configured the way you like it and the custom controls will remain, as that is part of core OctoPrint and the plugin just exposes the settings in the UI. It's either that are you are not running the release candidate version of the plugin that fixed it. Swith the release channel in the software update settings of OctoPrint for the plugin and set it to release candidate and upgrade when prompted. 

Thanks, will test that

**Comment by robfrawley** [comment] 2021-08-27 05:01
@jneilliii I was encountering the dragging issue described in this thread (due to the known plugin conflict(s) related to their respective inclusions of various jQuery Draggable UI component versions). Having switched to the latest RC release `0.1.7rc3` (by selecting and updating to "Release Candidate" for this plugin in the Octoprint "Software Update" configuration screen) I solved the dragging issue, _but now I have encountered a layout issue_.

The command that displays with a layout issue is a "PID Tuning (Nozzle & Bed)" command definition that accepts the following four variables:

1. The __nozzle temperature__ to perform the PID tuning at
2. The __fan speed (during nozzle tuning)__ to set
3. The __bed temperature__ to perform the PID tuning at
4. The __fan speed (during bed tuning)__ to set

Instead of displaying the command and its variable input dialogues `inline` within the configured column size, it breaks each component of the command (the name of each variable, the input for each variable, and the final command execution button) onto their own lines (as if each element was set to `display: block`), each sized to 100% of the configured column size.

Prior, each component of the custom command definition was sized to fit within the defined column size *as a complete unit*, with each component sized to the relevant percentage (depending on the number of variables) such that the entire command occupied a single line comprising 100% of the configured column size. So, given my example, with four variable names, four variable inputs, and the main execution button, each component would occupy `11.11%` (`100% / 9`) of the configured column width. *Now*, each command component occupies `100%` of the configured column width and therefore breaks onto as many lines as the number of compontnts.

<details>
  <summary>Click to Expand: <b>Plugin configuration of command with layout issue.</b></summary>

![Screen Shot 2021-08-27 at 12 43 42 AM](https://user-images.githubusercontent.com/3967713/131073392-4420eee3-fdb2-4232-a076-fea59d795d29.png)

</details>

<details>
  <summary>Click to Expand: <b>Layout issue with command component column width of <i>2</i>.</b></summary>

![Screen Shot 2021-08-27 at 12 36 59 AM](https://user-images.githubusercontent.com/3967713/131074053-54b92a95-4262-4c68-9b0f-631d98d87cbc.png)

</details>

<details>
  <summary>Click to Expand: <b>Layout issue with command component column width of <i>6</i>.</b></summary>

![Screen Shot 2021-08-27 at 12 44 48 AM](https://user-images.githubusercontent.com/3967713/131074023-54deb6ba-2cf0-4f11-b7b1-a69b82adb884.png)

</details>

I am running Octoprint `stable` at `v1.6.1` with a large collection of plugins.

<details>
  <summary>Click to Expand: <b>Installed plugin listing (JSON export)</b>.</summary>
  
```json
[
    {
        "key": "z_probe_offset",
        "name": "Z Probe Offset",
        "url": "https://framagit.org/razer/octoprint_z_probe_offset"
    },
    {
        "key": "uicustomizer",
        "name": "UI Customizer",
        "url": "https://github.com/LazeMSS/OctoPrint-UICustomizer"
    },
    {
        "key": "terminalmessaging",
        "name": "Terminal Messaging",
        "url": "https://github.com/jeffeb3/OctoPrint-TerminalMessaging"
    },
    {
        "key": "terminalcommandsextended",
        "name": "Terminal Commands Extended",
        "url": "https://github.com/jneilliii/OctoPrint-TerminalCommandsExtended"
    },
    {
        "key": "prusaslicerthumbnails",
        "name": "Slicer Thumbnails",
        "url": "https://github.com/jneilliii/OctoPrint-PrusaSlicerThumbnails"
    },
    {
        "key": "restorelevelingafterg28",
        "name": "Restore Leveling After G28",
        "url": "https://github.com/Xennis/OctoPrint-RestoreLevelingAfterG28"
    },
    {
        "key": "UltimakerFormatPackage",
        "name": "Cura Thumbnails",
        "url": "https://github.com/jneilliii/OctoPrint-UltimakerFormatPackage"
    },
    {
        "key": "simpleemergencystop",
        "name": "Simple Emergency Stop",
        "url": "https://github.com/Sebclem/OctoPrint-SimpleEmergencyStop"
    },
    {
        "key": "resource_monitor",
        "name": "Resource Monitor",
        "url": "https://github.com/Renaud11232/OctoPrint-Resource-Monitor"
    },
    {
        "key": "PrintTimeGenius",
        "name": "PrintTimeGenius Plugin",
        "url": "https://github.com/eyal0/OctoPrint-PrintTimeGenius"
    },
    {
        "key": "firmwareupdater",
        "name": "Firmware Updater",
        "url": "https://github.com/OctoPrint/OctoPrint-FirmwareUpdater"
    },
    {
        "key": "filemanager",
        "name": "FileManager",
        "url": "https://github.com/Salandora/OctoPrint-FileManager"
    },
    {
        "key": "filamentmanager",
        "name": "Filament Manager",
        "url": "https://github.com/OllisGit/OctoPrint-FilamentManager"
    },
    {
        "key": "detailedprogress",
        "name": "Detailed Progress",
        "url": "https://github.com/tpmullan/OctoPrint-DetailedProgress"
    },
    {
        "key": "dashboard",
        "name": "Dashboard",
        "url": "https://github.com/j7126/OctoPrint-Dashboard"
    },
    {
        "key": "costestimation",
        "name": "Cost Estimation",
        "url": "https://github.com/OllisGit/OctoPrint-CostEstimation"
    },
    {
        "key": "cancelobject",
        "name": "Cancel Objects",
        "url": "https://github.com/paukstelis/OctoPrint-Cancelobject"
    },
    {
        "key": "camerasettings",
        "name": "Camera Settings",
        "url": "https://github.com/The-EG/OctoPrint-CameraSettings"
    },
    {
        "key": "BetterHeaterTimeout",
        "name": "BetterHeaterTimeout",
        "url": "https://github.com/tjjfvi/OctoPrint-BetterHeaterTimeout"
    },
    {
        "key": "AutoTerminalInput",
        "name": "Auto Terminal Input",
        "url": "https://github.com/jneilliii/OctoPrint-AutoTerminalInput"
    },
    {
        "key": "autoscroll",
        "name": "Autoscroll",
        "url": "https://github.com/MoonshineSG/OctoPrint-Autoscroll"
    },
    {
        "key": "active_filters_extended",
        "name": "Active Filters Extended",
        "url": "https://github.com/jneilliii/OctoPrint-ActiveFiltersExtended"
    },
    {
        "key": "octodashcompanion",
        "name": "OctoDash Companion",
        "url": "https://github.com/jneilliii/OctoPrint-OctoDashCompanion"
    },
    {
        "key": "multilineterminal",
        "name": "Multi Line Terminal",
        "url": "https://github.com/jneilliii/OctoPrint-MultiLineTerminal"
    },
    {
        "key": "marlingcodedocumentation",
        "name": "Marlin GCode Documentation",
        "url": "https://github.com/costas-basdekis/MarlinGcodeDocumentation"
    },
    {
        "key": "eeprom_marlin",
        "name": "Marlin EEPROM Editor",
        "url": "https://github.com/cp2004/OctoPrint-EEPROM-Marlin."
    },
    {
        "key": "googledrivebackup",
        "name": "Google Drive Backup",
        "url": "https://github.com/jneilliii/OctoPrint-GoogleDriveBackup"
    },
    {
        "key": "DisplayLayerProgress",
        "name": "DisplayLayerProgress Plugin",
        "url": "https://github.com/OllisGit/OctoPrint-DisplayLayerProgress"
    },
    {
        "key": "calibrationcompanion",
        "name": "Calibration-Companion",
        "url": "https://github.com/iFrostizz/OctoPrint-CalibrationCompanion"
    },
    {
        "key": "bedlevelvisualizer",
        "name": "Bed Visualizer",
        "url": "https://github.com/jneilliii/OctoPrint-BedLevelVisualizer"
    },
    {
        "key": "backupscheduler",
        "name": "Backup Scheduler",
        "url": "https://github.com/jneilliii/OctoPrint-BackupScheduler"
    },
    {
        "key": "arc_welder",
        "name": "Arc-Welder",
        "url": "https://github.com/FormerLurker/ArcWelderPlugin"
    },
    {
        "key": "tempsgraph",
        "name": "Tempsgraph Plugin",
        "url": "https://github.com/1r0b1n0/OctoPrint-Tempsgraph"
    },
    {
        "key": "prettygcode",
        "name": "PrettyGCode",
        "url": "https://github.com/Kragrathea/OctoPrint-PrettyGCode"
    },
    {
        "key": "GcodeEditor",
        "name": "GcodeEditor",
        "url": "https://github.com/ieatacid/OctoPrint-GcodeEditor"
    },
    {
        "key": "octolapse",
        "name": "Octolapse",
        "url": "https://github.com/FormerLurker/Octolapse"
    }
]
```
</details>

Any idea why the layout issue cropped up after upgrading from this plugin's `stable` release channel to its `rc` channel? Thanks; I truly appreciate any help you can provide!

All the best.

**Comment by jneilliii** [comment] 2021-08-27 12:36
Probably related to unfinished css styling fixes.

**Comment by robfrawley** [comment] 2021-08-28 03:40
@jneilliii Anything in particular that you need help with to get such erroneous CSS definitions corrected (I don't want to take a look and put in time duplicating efforts if you are already actively working on such changes via a local dev branch)? If you'd like assistance expediting the RC version updates, feel free to let me know if any other components require updating (aside from the CSS) to correct this behavior and I'll likely have some extra time to take a look at it if needed.

Thanks again! All the best.

**Comment by jneilliii** [comment] 2021-08-28 06:33
@robfrawley if you want to take a look, by all means do. I'm not currently working on this plugin actively at the moment and if it's something that someone else could contribute that would be a huge help. The rc release of the plugin should match the rc branch here on the repo, so if you do decide to help make sure you're basing your work off that one. I'm also always open to improvements in code if you see anything done blatantly wrong or less efficient.

**Closed as completed** 2022-05-28 22:15 UTC
Labels: bug, solved
