### ISSUE TITLE
Suggestion (really not an issue)

### ISSUE THREAD

**Issue by pferlini63** [jneilliii/OctoPrint-TerminalCommandsExtended#6] opened 2020-03-21 06:54 UTC
Thanks again for this plugin, that works like a charms.

A question.

Its possible to insert a "row break" between buttons so they remain in order ?

In my case i would like to have : 
first row leveling buttons
second row load/unload commands
so on

but due to page arrange of html's the result is different from expectation ... as you can see in the image uploaded.

can you give me a suggestion on how to solve this "cosmetic" problem ? :-)

Paolo
![buttons](https://user-images.githubusercontent.com/44324595/77221320-093d0500-6b49-11ea-859a-d9d6b99536e5.jpg)

**Comment by jneilliii** [comment] 2020-03-21 14:51
Duplicate of #3 really, closing.

**Closed as completed by jneilliii** 2020-03-21 14:51 UTC
